name: 'PR gif generator'
description: 'Post GIF as comments for PRs based on type of the PR'
inputs:
  github-token:
    description: 'Pass in secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'